---
deployment:
 tasks:
 - export DEPLOYPATH=/home/aeeconference/
 - export PUBLICPATH=/home/aeeconference/public_html/
 - echo "Starting Maintenance mode..."
 - cd $DEPLOYPATH; php artisan down
 - echo "Copying..."
 - /bin/cp -R app $DEPLOYPATH
 - /bin/cp -R bootstrap $DEPLOYPATH
 - /bin/cp -R config $DEPLOYPATH
 - /bin/cp -R resources $DEPLOYPATH
 - /bin/cp -R routes $DEPLOYPATH
 - /bin/cp -R database $DEPLOYPATH
 - /bin/cp -R composer.json $DEPLOYPATH
 - /bin/cp -R public/favicon.ico $PUBLICPATH
 - /bin/cp -R public/index.php $PUBLICPATH
 - /bin/cp -R public/robots.txt $PUBLICPATH
 - /bin/cp -R public/assets $PUBLICPATH
 - /bin/cp -R public/assets-rtl $PUBLICPATH
 - /bin/cp -R public/scripts $PUBLICPATH
 - echo "Copy complete"
 - echo "Composer installing..."
 - cd $DEPLOYPATH; composer install
 - cd $DEPLOYPATH; composer update --no-dev
 - echo "Composer complete"
 - echo "Database Migrating..."
 - cd $DEPLOYPATH; php artisan migrate
 - echo "Database Migrating complete"
 - echo "Optimizing ..."
 - cd $DEPLOYPATH; php artisan optimize
 - cd $DEPLOYPATH; php artisan auth:clear-resets
#  - echo "Clearing Cache..."
#  - cd $DEPLOYPATH; php artisan view:clear
#  - cd $DEPLOYPATH; php artisan config:clear
#  - echo "Caching ..."
#  - cd $DEPLOYPATH; php artisan view:cache
#  - cd $DEPLOYPATH; php artisan config:cache
#  - cd $DEPLOYPATH; php artisan config:publish
 - echo "Deployment complete"
 - cd $DEPLOYPATH; php artisan up
 - echo "Maintenance mode End."
