---
deployment:
 tasks:
 - export DEPLOYPATH=/home/aeeconference/
 - export PUBLICPATH=/home/aeeconference/public_html/
 - echo "Copying..."
 - /bin/cp -R app $DEPLOYPATH
 - /bin/cp -R bootstrap $DEPLOYPATH
 - /bin/cp -R config $DEPLOYPATH
 - /bin/cp -R resources $DEPLOYPATH
 - /bin/cp -R routes $DEPLOYPATH
 - /bin/cp -R resources $DEPLOYPATH
 - /bin/cp -R composer.json $DEPLOYPATH
 - /bin/cp -R public/favicon.ico $PUBLICPATH
 - /bin/cp -R public/index.php $PUBLICPATH
 - /bin/cp -R public/robots.txt $PUBLICPATH
 - /bin/cp -R public/assets $PUBLICPATH
 - /bin/cp -R public/assets-rtl $PUBLICPATH
 - /bin/cp -R public/scripts $PUBLICPATH
 - echo "Copy complete"
 - echo "Composer installing..."
 - cd $DEPLOYPATH; composer install
 - cd $DEPLOYPATH; composer update --no-dev
 - echo "Composer complete"
#  - cd $DEPLOYPATH; sudo chmod -R 777 writable
 - echo "Database Migrating..."
 - /usr/local/bin/php /home/aeeconference/artisan migrate
 - echo "Database Migrating complete"
 - echo "Deployment complete"
