version: "3.7"
services:
  web-server:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - ".:/var/www/"
      - "./public/:/var/www/html/"
      - users-data:/var/www/html/writable/
    ports:
      - "80:80"
  mysql-server:
    platform: linux/x86_64
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
        - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - "./:/home/"
  phpmyadmin:
    platform: linux/x86_64
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "50000:80"
volumes:
  mysql-data:
  users-data:
